export {
    IconCloseX,
    IconArrowLeft,
    IconArrowRight,
    IconDanger,
    IconSuccess,
    IconTrushSquare,
    IconLogo,
    IconElips,
    IconLock,
    IconSearch,
    IconUser,
    IconPen,
    IconArrowDown,
    IconArrowUp,
    IconShortLogo,
    IconATelegramm,
    IconAVk,
    IconTelegramm,
    IconVk
} from "./Icons";